### ISSUE TITLE
Bold wiki text not parsed correctly

### ISSUE THREAD

**Issue by phlegx** [molybdenum-99/infoboxer#69]
Hi!

Here an example to reproduce the bug:

```ruby
paragraph = Infoboxer.wikipedia('it').get('Aritmetica').intro.first
```

The paragraph results in:

```ruby
paragraph.to_s
=> "L''''aritmetica (dal greco αριθμός = numero) ..."
```

The Wiki text is (word **aritmetica** is bold on Wiki):

`L''''aritmetica''' (dal [[Lingua greca|greco]] ''αριθμός'' = numero) ...`

and Infoboxer should return: 

`L'aritmetica (dal greco αριθμός = numero) ...`

**Comment by zverok** [comment]
Wow. This one is hard. Looking into it, too.

**Comment by zverok** [comment]
Fixed it in `develop` branch!
One small quirk: Wikipedia thinks it is (HTML equivalent) `L'<b>aritmetica</b>`, while Infoboxer considers rather `L<b>'aritmetica</b>`. But I hope for all practical purposes it is not that significant.
