### ISSUE TITLE
Infoboxer::Parser::ParsingError on Wiki (Unexpected break of template variables)

### ISSUE THREAD

**Issue by phlegx** [molybdenum-99/infoboxer#70]
Hi! I tried out your gem and if I do:

```ruby
Infoboxer.wikipedia('es').get('Peso')
```

I get:

```log
Infoboxer::Parser::ParsingError (Unexpected break of template variables: 
   [#<Var(<math>g): \frac{F}{m} = \frac {G M_T}de a...>, #<Var(1): El peso de un ser humano...>] at line 140:
```

**This is the line that makes problems:** `<math>g = \frac{F}{m} = \frac {G M_T}{{R_T}^2} </math>`
**Source:** https://es.wikipedia.org/w/index.php?title=Peso&action=edit

Wiki code snipped:

```
{{Ecuación|<math>g = \frac{F}{m} = \frac {G M_T}{{R_T}^2} </math>}}
```

**What can I do to solve this problem?**

**Comment by zverok** [comment]
Yeah, seems connected to #68

**Comment by zverok** [comment]
No, not connected to #68, it is different things :)

This one is fixed in `develop` branch, please check. (You can use "develop" branch by adding to `Gemfile` line like `gem 'infoboxer', git: 'https://github.com/molybdenum-99/infoboxer.git', branch: 'develop'`
