### ISSUE TITLE
Fails to parse these specific search results

### ISSUE THREAD

**Issue by Nakilon** [molybdenum-99/infoboxer#89]
I would love to replace `mediawiki-butt` with `infoboxer` but in this test it is unable to parse search results:
```ruby
query = "created by Stack Exchange users"
```
```ruby
require "mediawiki-butt"
butt = MediaWiki::Butt.new "https://esolangs.org/w/api.php"
result = butt.get_search_results query
result = butt.get_search_text_results query if result.empty?
p result
p "https:" + URI.escape(URI.escape(butt.get_article_path result.first), "?") unless result.empty?
```
```none
["???", "List of ideas"]
"https://esolangs.org/wiki/%3F%3F%3F"
```
```ruby
require "infoboxer"
p Infoboxer.wiki("https://esolangs.org/w/api.php").search(query, limit: 1).first
```
```none
nil
```
(also here it's 2-3 times slower than butt, maybe making more requests, idk)

**Comment by zverok** [comment]
By default, Infoboxer's search looks only in titles (I am not sure it is sensible behavior actually, but that's how it is now). You can hack it around by adjusting the request:
```ruby
Infoboxer.wiki("https://esolangs.org/w/api.php").search(query, limit: 1) { |req| req.what(:text) }
# => [#<Page(title: "???", url: "https://esolangs.org/wiki/%3F%3F%3F"): ??? is an esoteric programming ...>]
```
(`req` inside the block is [MediaWiktory::Wikipedia::Actions::Query](https://www.rubydoc.info/gems/mediawiktory/0.1.3/MediaWiktory/Wikipedia/Actions/Query), and on search, this [module](https://www.rubydoc.info/gems/mediawiktory/0.1.3/MediaWiktory/Wikipedia/Modules/GSearch) is available for additional tweaking)

> also here it's 2-3 times slower than butt, maybe making more requests

It fetches some meta-info about MediaWiki instance on wiki object instantiation, so if you'll do this:
```ruby
wiki = Infoboxer.wiki("https://esolangs.org/w/api.php") # meta-info fetching

wiki.search(...) # reusing the object
```
...it'll probably help.

**Comment by Nakilon** [comment]
The order is weird though.

![image](https://user-images.githubusercontent.com/2870363/133324633-def24062-18a9-4463-af5b-c3a80dd695f7.png)

```none
> wiki.search("nakilon", limit: 1){ |req| req.what :text }.first.title
=> "Velik"
> wiki.search("nakilon", limit: 2){ |req| req.what :text }.first.title
=> "RASEL"
> wiki.search("nakilon", limit: 3){ |req| req.what :text }.first.title
=> "RASEL"
> wiki.search("nakilon", limit: 2){ |_| _.what :text }.map &:title
=> ["RASEL", "Velik"]
```

P.S.: I already have the separate "meta-info fetching" line so there is probably something else that takes time.

**Comment by zverok** [comment]
> The order is weird though.

That's what their API do :shrug: 
* [With limit 1](https://esolangs.org/w/api.php?action=query&generator=search&gsrlimit=1&gsrsearch=nakilon&gsrwhat=text&inprop=url&prop=revisions%7Cinfo&redirects=true&rvprop=content%7Ctimestamp)
* [With limit 2](https://esolangs.org/w/api.php?action=query&generator=search&gsrlimit=2&gsrsearch=nakilon&gsrwhat=text&inprop=url&prop=revisions%7Cinfo&redirects=true&rvprop=content%7Ctimestamp)

**Comment by Nakilon** [comment]
Alright, thanks for the help. Now I fully switched to your gem: https://github.com/Nakilon/nakiircbot/commit/e35ce0783fbc27072f1c829cc2d80835a00c010f
